# Site
title: The Nightside
description: Welcome to the the otherside, where things get a little stranger every day!
url:
title: Halve
description: Stylish, Two-Column Jekyll Theme
url: https://taylantatli.github.io/Halve

logo: halve.png                                       # Site logo
locale: en_US

# Left Block Images
background:
  homepage: images/wallhaven-21827.jpg              # this image will be shown on homepage's left block
  post-list: images/wallhaven-52681.jpg             # this image will be shown on post list page
  default-post: images/wallhaven-254106.jpg          # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
#email:             email
#google.plus:        username
twitter:            qVintage
#facebook:           username
github:             balheru
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          valeriupot
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
flickr:             148211020@N03
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           valeriuioae278

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
